#!/usr/bin/env python3
"""Generate a ProofRail Composed Bronze Demo 001 claim YAML."""
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CLAIM_PATH = ROOT / "claims" / "bronze-claim-demo-001.yaml"


def sh(cmd: list[str]) -> str:
    return subprocess.check_output(cmd, cwd=ROOT, text=True).strip()


def exists(path: str) -> bool:
    return (ROOT / path).exists() and (ROOT / path).stat().st_size > 0


def read(path: str) -> str:
    p = ROOT / path
    return p.read_text() if p.exists() else ""


def main() -> None:
    manifest = json.loads((ROOT / "evidence" / "protected_actuator_set.json").read_text())
    actuator_hash = sh(["python3", "scripts/actuator_set_hash.py"])
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    evidence_items = {
        "architecture_notes": "docs/architecture.md",
        "runbook": "docs/runbook.md",
        "protected_actuator_set_manifest": "evidence/protected_actuator_set.json",
        "bypass_prevention_test": "evidence/bypass-test-results.md",
        "stop_control_test": "evidence/emergency-stop-test.md",
        "rate_limit_circuit_breaker_test": "evidence/rate-limit-test.md",
        "audit_sample": "evidence/audit-sample.jsonl",
        "performance_test": "evidence/latency-benchmark.md",
        "substrate_log_sample": "evidence/agentgateway-log-sample.txt",
    }

    missing = [p for p in evidence_items.values() if not exists(p)]

    stop_text = read("evidence/emergency-stop-test.md")
    rate_text = read("evidence/rate-limit-test.md")

    circuit_breaker_observed = "PASS: stop-control mode blocked tool call" in stop_text
    rate_limit_observed = "PASS: rate-limit/circuit-breaker behavior observed" in rate_text

    rate_limit_or_circuit_breaker = rate_limit_observed or circuit_breaker_observed

    yaml = f'''spec_version: "v0.1"
claim_type: "proofrail.bronze.composed"
claim_id: "proofrail-demo-001-{now.replace(':','').replace('-','')}"
claim_label: "ProofRail Composed Bronze Demo 001 — agentgateway MCP substrate — test env"
profile: "bronze"
mode: "enforce"
environment: "test"
surfaces_in_scope:
  - "mcp"

substrate:
  name: "agentgateway"
  type: "open-source MCP gateway"
  version_declared: "v1.2.1 docker image"
  role: "MCP mediation, routing, protocol session enforcement, and observability source"
  source_url: "https://github.com/agentgateway/agentgateway"

protected_actuator_set:
  name: "{manifest['name']}"
  surface: "{manifest['surface']}"
  hash: "{actuator_hash}"
  contents:
'''

    for item in manifest["contents"]:
        yaml += f'    - "{item}"\n'

    yaml += f'''
controls:
  declared_actuator_set: true
  gateway_mediation: true
  bypass_prevention_tested: true
  stop_control_demonstrated: {str(circuit_breaker_observed).lower()}
  rate_limit_or_circuit_breaker_demonstrated: {str(rate_limit_or_circuit_breaker).lower()}
  normalized_audit_evidence: true
  performance_measured: true
  runbook_present: true

control_details:
  rate_limit_observed: {str(rate_limit_observed).lower()}
  circuit_breaker_observed: {str(circuit_breaker_observed).lower()}
  note: "Demo 001 demonstrates circuit-breaker behavior through stop-control. agentgateway local rate-limit policy attachment remains unresolved."

control_mapping:
  gateway_mediation:
    component: "agentgateway"
    evidence: "evidence/agentgateway-log-sample.txt"
  bypass_prevention:
    component: "Docker Compose network segmentation + Docker secrets"
    evidence: "evidence/bypass-test-results.md"
  stop_control:
    component: "agentgateway target switch to stop-mcp server"
    evidence: "evidence/emergency-stop-test.md"
  rate_limit_circuit_breaker:
    component: "ProofRail stop-control circuit breaker; rate-limit pending"
    evidence: "evidence/rate-limit-test.md"
  audit_normalization:
    component: "ProofRail evidence scripts"
    evidence: "evidence/audit-sample.jsonl"

evidence:
'''

    for key, path in evidence_items.items():
        yaml += f'  {key}: "{path}"\n'

    yaml += f'''
validation:
  type: "self-attested-demo"
  validator: "ProofRail claim validator v0.1 structural check"
  generated_at: "{now}"
  missing_evidence_files: {json.dumps(missing)}

limitations:
  - "Demo 001 is a local Docker Compose test environment, not a production conformance assertion."
  - "Circuit-breaker behavior is demonstrated by stop-control mode."
  - "agentgateway local rate-limit behavior was not observed under the current config and remains a Demo 001b refinement."
  - "Stop control is implemented as a gateway target switch/restart for demo purposes; later demos should use dynamic policy or external authorization."
  - "The JSONL audit sample is normalized evidence generated by demo scripts from test activity, not a SIEM export."
'''

    CLAIM_PATH.write_text(yaml)
    print(CLAIM_PATH)

    if missing:
        print("WARNING: missing evidence files:", ", ".join(missing))


if __name__ == "__main__":
    main()
